<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.6"/>
    <xacro:property name="base_width" value="0.4"/>
    <xacro:property name="base_height" value="0.2"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>
    <xacro:property name="sphere_radius" value="0.05"/>

    <joint name="base_foot_base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${sphere_radius}" rpy="0.0 0.0 0.0"/>
        <axis xyz="0 1 0"/>
        
    </joint>

    <joint name="base_first" type="continuous">
        <parent link="base_link"/>
        <child link="first_wheel"/>
        <origin xyz="${-base_length/4.0} -0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="base_second" type="continuous">
        <parent link="base_link"/>
        <child link="second_wheel"/>
        <origin xyz="${-base_length/4.0} 0.225 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

  <joint name="base_sphere" type="continuous">
        <parent link="base_link"/>
        <child link="sphere"/>
        <origin xyz="${base_length/3.0} 0 -0.05" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint> 

    <link name="base_footprint">
    </link>

    <link name="base_link"> 
        <visual>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
            <material name="green">
            </material>
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}"/>
            </geometry>
            <origin xyz="0 0 0.1" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="10.0" l="${2*base_length}" w="${2*base_width}" h="${2*base_height}"
                        xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
    </link>
    
    <xacro:macro name="wheel" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
                <material name="grey">
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
            </collision>
            <xacro:cylinder_interia m="1.0" r="${2*wheel_radius}" h="${2*wheel_length}" xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
        </link>
    </xacro:macro>

    <xacro:wheel prefix="first" />
    <xacro:wheel prefix="second" />

 <link name="sphere">
        <visual>
            <geometry>
                <sphere radius="${sphere_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="grey">
            </material>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${sphere_radius}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:sphere_inertia m="0.5" r="${wheel_radius/2.0}" xyz="0 0 0" rpy="0 0 0"/>
    </link>   

    
    
</robot>
