<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="laser_radius" value="0.05"/>
    <xacro:property name="laser_length" value="0.025"/>
    
    <link name="ray_link">
      <visual>
          <geometry>
              <cylinder radius="${laser_radius}" length="${laser_length}"/>
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0"/>
          <material name="grey">
          </material>
      </visual>
      <collision>
          <geometry>
              <cylinder radius="${laser_radius}" length="${laser_length}"/>
          </geometry>
          <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <xacro:cylinder_interia m="1.0" r="${2*laser_radius}" h="${2*laser_length}" xyz="0 0 0" rpy="${pi/2.0} 0 0"/>
  </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="ray_link"/>
        <origin xyz="0 0 ${(base_height)+(laser_length/2.0)}" rpy="0.0 0.0 0.0"/>
    </joint>
    
    <!-- hokuyo -->
  <gazebo reference="ray_link">
    <material>
      Gazebo/Red
    </material>
    <sensor type="ray" name="laser">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>360</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>0.30</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
  
      </ray>
      <plugin name="laser_controller" filename="libgazebo_ros_ray_sensor.so">
        <ros>
          <argument>~/out:=scan</argument>
        </ros>
        <output_type>sensor_msgs/LaserScan</output_type>
        <frame_name>ray_link</frame_name>
      </plugin>
    </sensor>
  </gazebo>

</robot>